# Site settings
title: 2018, Central Asia
subtitle: "A journal of a journey"
email: 
description: "A short journal of Prisca’s and Simone’s journey through China, Xinjiang, Kyrgyzstan and Uzbekistan."
baseurl: "/"
url: "http://centralasia2018.viteinfinite.com"
twitter_username: "viteinfinite"
github_username:  "viteinfinite"
instagram_username: "ca_pris"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Google Maps
maps:
  apiKey: "AIzaSyB8Q8bgrac8jveEGu22j9ltVjcaI825viE"
  style: "feature:administrative|element:labels.text.fill|color:0x444444&style=feature:landscape|element:all|color:0xf2f2f2&style=feature:landscape|element:geometry.fill|visibility:on&style=feature:landscape.man_made|element:geometry.fill|hue:0xffd100|saturation:44&style=feature:landscape.man_made|element:geometry.stroke|saturation:-1|hue:0xff0000&style=feature:landscape.natural|element:geometry|saturation:-16&style=feature:landscape.natural|element:geometry.fill|hue:0xffd100|saturation:44&style=feature:poi|element:all|visibility:off&style=feature:road|element:all|saturation:-30|lightness:12|hue:0xff8e00&style=feature:road.highway|element:all|visibility:simplified|saturation:-26&style=feature:road.arterial|element:labels.icon|visibility:off&style=feature:transit|element:all|visibility:off&style=feature:water|element:all|color:0xc0b78d|visibility:on|saturation:4|lightness:40&style=feature:water|element:geometry|hue:0xffe300&style=feature:water|element:geometry.fill|hue:0xffe300|saturation:-3|lightness:-10&style=feature:water|element:labels|hue:0xff0000|saturation:-100|lightness:-5&style=feature:water|element:labels.text.fill|visibility:off&style=feature:water|element:labels.text.stroke|visibility:off"

# Sass
sass:
    style: :compressed

# Plugins
plugins:
  - jekyll-paginate
