# Site settings
title: 2018, Central Asia
subtitle: "Journal of Simone and Prisca"
email: 
description: "This is a short blog of our journey through China, Xinjiang, Kyrgyzstan and Uzbekistan."
baseurl: "/"
url: "http://centralasia2018.viteinfinite.com"
twitter_username: "viteinfinite"
github_username:  "viteinfinite"
instagram_username: "viteinfinite"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

# Plugins
plugins:
  - jekyll-paginate
